# Static parameters fsm stand up for a1 real
standup:
  Kp_joint0: 80
  Kp_joint1: 50
  Kp_joint2: 50

  Kd_joint0: 3
  Kd_joint1: 3
  Kd_joint2: 3

  Kp_cartesian_x: 1000
  Kp_cartesian_y: 1000
  Kp_cartesian_z: 1000

  Kd_cartesian_x: 15
  Kd_cartesian_y: 15
  Kd_cartesian_z: 15

#-------------------------------
static_params:
  max_vel_x: 0.7
  max_vel_y: 0.4
  max_turn_rate: 2.5

  Q_roll: 10
  Q_pitch: 10
  Q_yaw: 15
  Q_x: 1
  Q_y: 1
  Q_z: 30
  Q_w_roll: 0.5
  Q_w_pitch: 0.5
  Q_w_yaw: 3
  Q_vx: 10
  Q_vy: 10
  Q_vz: 5

